// mlkit_zh_labels.dart
// ML Kit ImageLabeler 英文标签 → 中文静态翻译词典。
// ML Kit bundled on-device 模型约返回 400+ 个标准化英文标签。
// 本词典尽量覆盖全量标签，未覆盖的回退返回原始英文。
// 匹配策略：精确匹配 → 小写匹配 → 返回原文

/// ML Kit ImageLabeler 的中文标签词典。
/// 用法：MlKitZhLabels.translate("Dog") → "狗"
class MlKitZhLabels {
  // 未匹配时返回原文
  static String translate(String en) =>
      _map[en] ?? _map[en.toLowerCase()] ?? en;

  static const Map<String, String> _map = {

    // ── 动物（哺乳类）─────────────────────────────────────────────────────
    'Animal': '动物',
    'Dog': '狗',
    'Cat': '猫',
    'Bird': '鸟',
    'Fish': '鱼',
    'Horse': '马',
    'Cattle': '牛',
    'Sheep': '羊',
    'Pig': '猪',
    'Rabbit': '兔子',
    'Chicken': '鸡',
    'Duck': '鸭子',
    'Goose': '鹅',
    'Deer': '鹿',
    'Bear': '熊',
    'Wolf': '狼',
    'Fox': '狐狸',
    'Elephant': '大象',
    'Tiger': '老虎',
    'Lion': '狮子',
    'Panda': '熊猫',
    'Giant Panda': '大熊猫',
    'Monkey': '猴子',
    'Snake': '蛇',
    'Turtle': '乌龟',
    'Frog': '青蛙',
    'Insect': '昆虫',
    'Butterfly': '蝴蝶',
    'Bee': '蜜蜂',
    'Spider': '蜘蛛',
    'Crab': '螃蟹',
    'Shrimp': '虾',
    'Dolphin': '海豚',
    'Whale': '鲸鱼',
    'Shark': '鲨鱼',
    'Penguin': '企鹅',
    'Pet': '宠物',
    'Wildlife': '野生动物',
    'Marine mammal': '海洋哺乳动物',
    'Gerbil': '沙鼠',
    'Camel': '骆驼',
    'Giraffe': '长颈鹿',
    'Zebra': '斑马',
    'Hippopotamus': '河马',
    'Rhinoceros': '犀牛',
    'Crocodile': '鳄鱼',
    'Parrot': '鹦鹉',
    'Flamingo': '火烈鸟',
    'Eagle': '老鹰',
    'Owl': '猫头鹰',
    'Squirrel': '松鼠',
    'Hedgehog': '刺猬',
    'Dog breed': '犬种',
    'Shetland Sheepdog': '喜乐蒂牧羊犬',
    'Himalayan': '喜马拉雅猫',
    'Pomacentridae': '雀鲷鱼',
    'Boxer': '拳师犬',
    'Goldfish': '金鱼',
    'Hamster': '仓鼠',
    'Guinea pig': '豚鼠',

    // ── 人 ────────────────────────────────────────────────────────────────
    'Person': '人',
    'Human': '人',
    'People': '人群',
    'Face': '人脸',
    'Facial expression': '表情',
    'Smile': '微笑',
    'Laugh': '大笑',
    'Selfie': '自拍',
    'Child': '儿童',
    'Baby': '婴儿',
    'Boy': '男孩',
    'Girl': '女孩',
    'Man': '男性',
    'Woman': '女性',
    'Crowd': '人群',
    'Group': '群体',
    'Family': '家庭',
    'Friendship': '友情',
    'Couple': '情侣',
    'Portrait': '人像',
    'Interaction': '互动',
    'Community': '社群',
    'Sitting': '坐姿',
    'Eating': '进食',
    'Beard': '胡须',
    'Toe': '脚趾',

    // ── 服装与时尚 ────────────────────────────────────────────────────────
    'Fashion': '时尚',
    'Clothing': '服装',
    'Dress': '连衣裙',
    'Shirt': '衬衫',
    'Jeans': '牛仔裤',
    'Hat': '帽子',
    'Glasses': '眼镜',
    'Sunglasses': '墨镜',
    'Shoe': '鞋',
    'Bag': '包',
    'Jewelry': '首饰',
    'Necklace': '项链',
    'Bracelet': '手链',
    'Shorts': '短裤',
    'Swimwear': '泳衣',
    'Wetsuit': '潜水服',
    'Tie': '领带',
    'Tights': '紧身裤',

    // ── 自然与户外 ────────────────────────────────────────────────────────
    'Outdoor': '户外',
    'Nature': '自然',
    'Landscape': '风景',
    'Sky': '天空',
    'Cloud': '云',
    'Sunset': '日落',
    'Sunrise': '日出',
    'Sun': '太阳',
    'Moon': '月亮',
    'Star': '星星',
    'Night': '夜晚',
    'Daytime': '白天',
    'Mountain': '山',
    'Hill': '丘陵',
    'Valley': '山谷',
    'River': '河流',
    'Lake': '湖泊',
    'Ocean': '海洋',
    'Sea': '大海',
    'Beach': '海滩',
    'Wave': '海浪',
    'Waterfall': '瀑布',
    'Desert': '沙漠',
    'Forest': '森林',
    'Tree': '树木',
    'Flower': '花卉',
    'Rose': '玫瑰',
    'Cherry blossom': '樱花',
    'Plant': '植物',
    'Grass': '草地',
    'Leaf': '树叶',
    'Agriculture': '农业',
    'Field': '田野',
    'Farm': '农场',
    'Snow': '雪',
    'Ice': '冰',
    'Rain': '雨',
    'Fog': '雾',
    'Rainbow': '彩虹',
    'Rock': '岩石',
    'Cliff': '悬崖',
    'Soil': '土壤',
    'Sand': '沙子',
    'Reef': '礁石',
    'Iceberg': '冰山',
    'Cave': '洞穴',
    'Underwater': '水下',
    'Jungle': '丛林',
    'Twig': '细枝',
    'Petal': '花瓣',
    'Wetland': '湿地',

    // ── 食物与饮品 ────────────────────────────────────────────────────────
    'Food': '食物',
    'Drink': '饮品',
    'Meal': '餐食',
    'Breakfast': '早餐',
    'Lunch': '午餐',
    'Dinner': '晚餐',
    'Snack': '零食',
    'Dessert': '甜品',
    'Cake': '蛋糕',
    'Bread': '面包',
    'Pizza': '披萨',
    'Hot dog': '热狗',
    'Cheeseburger': '芝士汉堡',
    'Noodle': '面条',
    'Rice': '米饭',
    'Dumpling': '饺子',
    'Sushi': '寿司',
    'Bento': '便当',
    'Meat': '肉类',
    'Chicken meat': '鸡肉',
    'Beef': '牛肉',
    'Pork': '猪肉',
    'Seafood': '海鲜',
    'Vegetable': '蔬菜',
    'Fruit': '水果',
    'Apple': '苹果',
    'Banana': '香蕉',
    'Orange': '橙子',
    'Grape': '葡萄',
    'Strawberry': '草莓',
    'Watermelon': '西瓜',
    'Coffee': '咖啡',
    'Tea': '茶',
    'Juice': '果汁',
    'Beer': '啤酒',
    'Wine': '红酒',
    'Chocolate': '巧克力',
    'Ice cream': '冰淇淋',
    'Soup': '汤',
    'Salad': '沙拉',
    'Egg': '鸡蛋',
    'Cheese': '奶酪',
    'Milk': '牛奶',
    'Mushroom': '蘑菇',
    'Fast food': '快餐',
    'Baked goods': '烘焙食品',
    'Cuisine': '菜肴',
    'Cookware and bakeware': '烹饪器具',
    'Sink': '水槽',

    // ── 建筑与城市 ────────────────────────────────────────────────────────
    'Building': '建筑',
    'Architecture': '建筑物',
    'House': '房屋',
    'Home': '家',
    'Apartment': '公寓',
    'Room': '房间',
    'Interior': '室内',
    'Bedroom': '卧室',
    'Kitchen': '厨房',
    'Bathroom': '浴室',
    'Living room': '客厅',
    'Office': '办公室',
    'City': '城市',
    'Street': '街道',
    'Road': '道路',
    'Bridge': '桥梁',
    'Tower': '塔楼',
    'Skyscraper': '摩天大楼',
    'Church': '教堂',
    'Temple': '寺庙',
    'Mosque': '清真寺',
    'Palace': '宫殿',
    'Museum': '博物馆',
    'School': '学校',
    'Hospital': '医院',
    'Market': '市场',
    'Restaurant': '餐厅',
    'Shop': '商店',
    'Store': '门店',
    'Mall': '商场',
    'Hotel': '酒店',
    'Stadium': '体育场',
    'Airport': '机场',
    'Railway station': '火车站',
    'Parking lot': '停车场',
    'Park': '公园',
    'Garden': '花园',
    'Playground': '游乐场',
    'Swimming pool': '游泳池',
    'Fence': '围栏',
    'Door': '门',
    'Window': '窗户',
    'Wall': '墙壁',
    'Floor': '地板',
    'Roof': '屋顶',
    'Stairs': '楼梯',
    'Corridor': '走廊',
    'Factory': '工厂',
    'Construction': '建筑工地',
    'Infrastructure': '基础设施',
    'Pier': '码头',
    'Pier (structure)': '码头',
    'Bar': '酒吧',
    'Cabinetry': '橱柜',
    'Brick': '砖块',
    'Poster': '海报',
    'Shipwreck': '海难',

    // ── 交通工具 ──────────────────────────────────────────────────────────
    'Vehicle': '交通工具',
    'Car': '汽车',
    'Truck': '卡车',
    'Bus': '公交车',
    'Motorcycle': '摩托车',
    'Bicycle': '自行车',
    'Train': '火车',
    'Airplane': '飞机',
    'Helicopter': '直升机',
    'Boat': '船',
    'Ship': '轮船',
    'Subway': '地铁',
    'Taxi': '出租车',
    'Van': '面包车',
    'Scooter': '电动车',
    'Military vehicle': '军用车辆',
    'Tractor': '拖拉机',
    'Sled': '雪橇',
    'Wheelbarrow': '手推车',
    'Junk': '帆船',
    'Windshield': '挡风玻璃',
    'Brig': '双桅帆船',

    // ── 电子设备与科技 ────────────────────────────────────────────────────
    'Technology': '科技',
    'Electronics': '电子产品',
    'Computer': '电脑',
    'Laptop': '笔记本电脑',
    'Mobile phone': '手机',
    'Smartphone': '智能手机',
    'Tablet computer': '平板电脑',
    'Camera': '相机',
    'Television': '电视',
    'Headphones': '耳机',
    'Keyboard': '键盘',
    'Screen': '屏幕',
    'Robot': '机器人',
    'Game controller': '游戏手柄',
    'Product': '产品',

    // ── 运动与活动 ────────────────────────────────────────────────────────
    'Sport': '运动',
    'Sports': '体育',
    'Football': '足球',
    'Basketball': '篮球',
    'Baseball': '棒球',
    'Tennis': '网球',
    'Badminton': '羽毛球',
    'Swimming': '游泳',
    'Running': '跑步',
    'Cycling': '骑行',
    'Yoga': '瑜伽',
    'Gym': '健身房',
    'Hiking': '徒步',
    'Climbing': '攀岩',
    'Skiing': '滑雪',
    'Surfing': '冲浪',
    'Dance': '舞蹈',
    'Exercise': '锻炼',
    'Competition': '比赛',
    'Team': '团队',
    'Windsurfing': '帆板运动',
    'Rafting': '漂流',
    'Camping': '露营',
    'Caving': '洞穴探险',
    'Safari': '野外探险',
    'Surfboard': '冲浪板',
    'Roller': '滚轴',
    'Prom': '舞会',
    'Graduation': '毕业典礼',
    'Bullfighting': '斗牛',
    'Picnic': '野餐',

    // ── 艺术、音乐、娱乐 ──────────────────────────────────────────────────
    'Art': '艺术',
    'Music': '音乐',
    'Concert': '演唱会',
    'Guitar': '吉他',
    'Piano': '钢琴',
    'Violin': '小提琴',
    'Drum': '鼓',
    'Performance': '表演',
    'Movie': '电影',
    'Party': '派对',
    'Festival': '节日',
    'Wedding': '婚礼',
    'Birthday': '生日',
    'Fireworks': '烟花',
    'Candle': '蜡烛',
    'Balloon': '气球',
    'Gift': '礼物',
    'Toy': '玩具',
    'Game': '游戏',
    'Book': '书籍',
    'Drawing': '绘画',
    'Sculpture': '雕塑',
    'Photography': '摄影',
    'Wreath': '花环',
    'Circus': '马戏团',
    'Aquarium': '水族馆',
    'Bonfire': '篝火',
    'Comics': '漫画',
    'Casino': '赌场',
    'Ferris wheel': '摩天轮',
    'Watercolor paint': '水彩画',
    'Statue': '雕像',
    'Porcelain': '瓷器',

    // ── 日常物品 ──────────────────────────────────────────────────────────
    'Furniture': '家具',
    'Chair': '椅子',
    'Table': '桌子',
    'Sofa': '沙发',
    'Bed': '床',
    'Lamp': '灯',
    'Mirror': '镜子',
    'Shelf': '书架',
    'Curtain': '窗帘',
    'Pillow': '枕头',
    'Cushion': '坐垫',
    'Bottle': '瓶子',
    'Cup': '杯子',
    'Glasses (Drinkware)': '杯子',
    'Bowl': '碗',
    'Plate': '盘子',
    'Knife': '刀',
    'Fork': '叉子',
    'Spoon': '勺子',
    'Umbrella': '雨伞',
    'Flower bouquet': '花束',
    'Clock': '时钟',
    'Watch': '手表',
    'Pen': '笔',
    'Paper': '纸张',
    'Box': '盒子',
    'Bag (container)': '袋子',
    'Backpack': '背包',

    // ── 文字与界面 ────────────────────────────────────────────────────────
    'Text': '文字',
    'Document': '文件',
    'Logo': 'Logo',
    'Sign': '标牌',
    'Screenshot': '截图',
    'Diagram': '图表',
    'Map': '地图',
    'Infographic': '信息图',

    // ── 场景与氛围 ────────────────────────────────────────────────────────
    'Black and white': '黑白',
    'Monochrome': '单色',
    'Colorfulness': '色彩丰富',
    'Macro photography': '微距摄影',
    'Aerial photography': '航拍',
    'Night photography': '夜景摄影',
    'Long exposure': '长曝光',
    'Silhouette': '剪影',
    'Reflection': '倒影',
    'Shadow': '阴影',
    'Texture': '纹理',
    'Pattern': '图案',
    'Abstract': '抽象',

    // ── 健康与医疗 ────────────────────────────────────────────────────────
    'Health': '健康',
    'Medicine': '医疗',
    'Doctor': '医生',
    'Hospital (Healthcare)': '医院',

    // ── 旅行与地标 ────────────────────────────────────────────────────────
    'Travel': '旅行',
    'Tourism': '旅游',
    'Landmark': '地标',
    'Vacation': '度假',
    'Luggage': '行李',
    'Passport': '护照',
    'Eiffel Tower': '埃菲尔铁塔',
    'Big Ben': '大本钟',
    'Statue of Liberty': '自由女神像',
    'Great Wall': '长城',

    // ── 自然现象与抽象 ────────────────────────────────────────────────────
    'Fire': '火',
    'Smoke': '烟雾',
    'Explosion': '爆炸',
    'Lightning': '闪电',
    'Earthquake': '地震',
    'Flood': '洪水',
    'Wind': '风',
    'Space': '太空',
    'Galaxy': '星系',
    'Planet': '星球',
    'Astronaut': '宇航员',

    // ── 颜色描述 ──────────────────────────────────────────────────────────
    'Red': '红色',
    'Blue': '蓝色',
    'Green': '绿色',
    'Yellow': '黄色',
    'Orange': '橙色',
    'Purple': '紫色',
    'Pink': '粉色',
    'White': '白色',
    'Black': '黑色',
    'Brown': '棕色',
    'Grey': '灰色',
    'Gray': '灰色',
    'Gold': '金色',
    'Silver': '银色',

    // ── 情感与概念（知识图谱）────────────────────────────────────────────
    'Love': '爱',
    'Happiness': '幸福',
    'Sadness': '悲伤',
    'Fun': '乐趣',
    'Adventure': '冒险',
    'Luxury': '奢华',
    'Vintage': '复古',
    'Modern': '现代',
    'Traditional': '传统',
    'Cute': '可爱',
    'Funny': '搞笑',
  };
}
